### ISSUE TITLE
Crash on demo app on font change

### ISSUE THREAD

**Issue by kelvinwatson** [commonsguy/cwac-richedit#32]
When changing the font (e.g. to monospace, san-serif), I encountered this crash:

    com.commonsware.cwac.richedit.demo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.commonsware.cwac.richedit.demo, PID: 5111
    java.lang.IndexOutOfBoundsException: setSpan (-1 ... -1) starts before 0
    at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1270)
    at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:684)
    at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:677)
    at com.commonsware.cwac.richedit.TypefaceEffect.applyToSpannable(TypefaceEffect.java:65)
    at com.commonsware.cwac.richedit.TypefaceEffect.applyToSelection(TypefaceEffect.java:37)
    at com.commonsware.cwac.richedit.TypefaceEffect.applyToSelection(TypefaceEffect.java:21)
    at com.commonsware.cwac.richedit.RichEditText.applyEffect(RichEditText.java:252)
    at com.commonsware.cwac.richedit.RichEditText.doAction(RichEditText.java:347)
    at com.commonsware.cwac.richedit.EditorActionModeCallback$Native.onActionItemClicked(EditorActionModeCallback.java:113)
    at com.android.internal.policy.DecorView$ActionModeCallback2Wrapper.onActionItemClicked(DecorView.java:2256)
    at com.android.internal.app.WindowDecorActionBar$ActionModeImpl.onMenuItemSelected(WindowDecorActionBar.java:1119)
    at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:761)
    at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
    at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:904)
    at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:894)
    at android.widget.ActionMenuView.invokeItem(ActionMenuView.java:616)
    at com.android.internal.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:152)
    at android.view.View.performClick(View.java:5610)
    at android.view.View$PerformClick.run(View.java:22260)
    at android.os.Handler.handleCallback(Handler.java:751)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6077)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by commonsguy** [comment]
@kelvinwatson What specific steps should I take to reproduce the crash?

**Comment by watsokel** [comment]
@commonsguy To reproduce, open the demo app in an emulator running API 24, type anything, and try changing the font to any font.

**Comment by commonsguy** [comment]
@watsokel There is a bug visible in the demo app, where if you choose the "Add CW Link" overflow item, it adds the text and the formatting action mode shows up. The action mode should only appear when text is selected. I think this bug is in the demo app, more so than the library, but I will look into it.
